# early version 
name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: 20
          cache: npm

      - name: Install
        run: npm ci

      - name: Create .env for CI
        run: |
           echo "CSV_PATH=../data/metacritic_games_test_data.csv" >> .env
           echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env

      - name: run seed scrip
        run: npm run etl

      - name: Run tests
        run: npm test

  deploy:
    if:
      (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
      (github.event_name == 'pull_request' && github.actor == 'noomde')
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        run: echo "Deploy in railway automatically if src is changed"
